apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: POSTGRES_URI
          value: postgresql://postgres:password@postgresql:5432/todos

